### ISSUE TITLE
Option decoder for Scala 3.2

### ISSUE THREAD

**Issue by ex0ns** [zio/zio-json#780]
I have the following code:

```scala
import zio._
import zio.json._
import zio.json.ast._
import scala.io.Source

final case class SyncState(
  @jsonField("next_batch") nextBatch: String,
  // @jsonField("account_data") accountData: Option[AccountData] = None
  @jsonField("account_data") accountData: Option[String]
)

object Main extends ZIOAppDefault {
  implicit lazy val syncStateDecoder: JsonDecoder[SyncState] = DeriveJsonDecoder.gen
  
  val content = Source.fromFile("file.json").getLines().mkString
  
  override def run =
    ZIO.fromEither(content.fromJson[Json].flatMap(_.as[SyncState])).debug
    // ZIO.fromEither(content.fromJson[SyncState]).debug
}
```

That I cross compile for 2.12, 2.13 and 3.2, and I get the following output
```bash
[45/129] examples[2.12.17].run 
SyncState(s737036_20146721_28996_716058_326898_115_59067_740531_0,None)
[87/129] examples[2.13.10].run 
SyncState(s737036_20146721_28996_716058_326898_115_59067_740531_0,None)
[129/129] examples[3.2.0].run 
<FAIL> Fail(Missing fields: account_data,Stack trace for thread "zio-fiber-4":
        at <empty>.Main.run(Main.scala:19))
timestamp=2022-11-10T17:45:29.830296Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" java.lang.String: Missing fields: account_data
        at <empty>.Main.run(Main.scala:19)"
```

Note that I've added the `"-Yretain-trees"` flag to my compiler for Scala 3.
My build file look like that (mill):
```scala
import mill._
import scalalib._
import mill.scalalib._

object Versions {
  val zioVersion     = "2.0.3"
  val zioJsonVersion = "0.3.0"
}

val scalaVersions = List("2.12.17", "2.13.10", "3.2.0")

abstract class ExtendedCrossScalaModule(crossScalaVersion: String) extends CrossScalaModule {

  override def scalacOptions =
    if (crossScalaVersion.startsWith("3."))
      Seq("-Yretain-trees")
    else
      Seq.empty[String]
}

object examples extends Cross[ExamplesModule](scalaVersions: _*)

class ExamplesModule(val crossScalaVersion: String) extends ExtendedCrossScalaModule(crossScalaVersion) {
  import Versions._

  def mainClass               = Some("Main")
  override def finalMainClass = T("Main")

  override def ivyDeps = Agg(
    ivy"dev.zio::zio:${zioVersion}",
    ivy"dev.zio::zio-json:${zioJsonVersion}"
  )
}
```
and the `file.json` that I'm using to reproduce the crash
```json
{
    "next_batch": "s737036_20146721_28996_716058_326898_115_59067_740531_0",
    "device_unused_fallback_key_types": []
}
```

I was not able to reproduce that in my tests, this is only happened (as far as I could say) when running the application. I also tried to package it inside a jar and a docker to make sure that this was not related to mill/the build, but I could still reproduce, I don't know why this is not triggered inside my tests.

If I set a default value to the option (such as None), it works fine (for the three version), I guess I could go with that for now, but there is still something fishy going on here I think.
I could try to have a look at this issue, but I don't really know zio-json source code and would like some pointers on where to start looking for that bug.

I think this might be related to #779 

Edit: I'm in fact (with no surprise) able to reproduce it in my tests:
```scala
import zio._
import zio.test._
import zio.test.Assertion._
import zio.json._
import Main._

object MainSpec extends ZIOSpecDefault {

  def spec = suite("test")(
    test("json") {
      val content = """ 
{
    "next_batch": "s737036_20146721_28996_716058_326898_115_59067_740531_0",
    "device_unused_fallback_key_types": []
}
            """
      assert(content.fromJson[SyncState])(
        isRight(equalTo(SyncState("s737036_20146721_28996_716058_326898_115_59067_740531_0", None)))
      )
    }
  )
}
```

**Comment by ex0ns** [comment]
I'm a bit confused, I cloned this repo, took the code at the tag `v0.3.0` and add the following test:

```diff
From 8a8fe7ad51eb59bf6f3dc989c62b074048882f1a Mon Sep 17 00:00:00 2001
From: ex0ns <mail@mail.com>
Date: Thu, 10 Nov 2022 21:03:14 +0100
Subject: [PATCH] spec

---
 .../src/test/scala/zio/json/DecoderSpec.scala | 36 +++++++++++++++++++
 1 file changed, 36 insertions(+)

diff --git a/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala b/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala
index e48865b..12a840b 100644
--- a/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala
+++ b/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala
@@ -70,6 +70,42 @@ object DecoderSpec extends ZIOSpecDefault {
           assert("""{"s":""}""".fromJson[OnlyString])(isRight(equalTo(OnlyString("")))) &&
           assert("""{"s":"","t":""}""".fromJson[OnlyString])(isLeft(equalTo("(invalid extra field)")))
         },
+        test("option syncstate - 1") {
+          final case class SyncState(
+            @jsonField("next_batch") nextBatch: String,
+            @jsonField("account_data") accountData: Option[String]
+          )
+
+          implicit val syncStateDecoder: JsonDecoder[SyncState] = DeriveJsonDecoder.gen
+
+          val content = """ 
+{
+    "next_batch": "s737036_20146721_28996_716058_326898_115_59067_740531_0",
+    "device_unused_fallback_key_types": []
+}
+            """
+          assert(content.fromJson[Json].flatMap(_.as[SyncState](syncStateDecoder)))(
+            isRight(equalTo(SyncState("s737036_20146721_28996_716058_326898_115_59067_740531_0", None)))
+          )
+        },
+        test("option syncstate - 2") {
+          final case class SyncState(
+            @jsonField("next_batch") nextBatch: String,
+            @jsonField("account_data") accountData: Option[String]
+          )
+
+          implicit val syncStateDecoder: JsonDecoder[SyncState] = DeriveJsonDecoder.gen
+
+          val content = """ 
+{
+    "next_batch": "s737036_20146721_28996_716058_326898_115_59067_740531_0",
+    "device_unused_fallback_key_types": []
+}
+            """
+          assert(content.fromJson[SyncState](syncStateDecoder))(
+            isRight(equalTo(SyncState("s737036_20146721_28996_716058_326898_115_59067_740531_0", None)))
+          )
+        },
         test("option") {
           case class WithOpt(id: Int, opt: Option[Int])
           implicit val decoder: JsonDecoder[WithOpt] = DeriveJsonDecoder.gen
-- 
2.34.1


```

And then ran the tests with `sbt '++3.1.3 zioJsonJVM/test'` and the first test did not pass, the second one did pass.
I totally get that the first way of writing the code with the flatMap is not a good idea, and probably wrong, but it passes on 2.13 and 2.13 but not in 3.0.

**Comment by ex0ns** [comment]
I'm a bit confused, I cloned this repo, took the code at the tag `v0.3.0` and add the following test:

```diff
From 8a8fe7ad51eb59bf6f3dc989c62b074048882f1a Mon Sep 17 00:00:00 2001
From: ex0ns <mail@mail.com>
Date: Thu, 10 Nov 2022 21:03:14 +0100
Subject: [PATCH] spec

---
 .../src/test/scala/zio/json/DecoderSpec.scala | 36 +++++++++++++++++++
 1 file changed, 36 insertions(+)

diff --git a/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala b/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala
index e48865b..12a840b 100644
--- a/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala
+++ b/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala
@@ -70,6 +70,42 @@ object DecoderSpec extends ZIOSpecDefault {
           assert("""{"s":""}""".fromJson[OnlyString])(isRight(equalTo(OnlyString("")))) &&
           assert("""{"s":"","t":""}""".fromJson[OnlyString])(isLeft(equalTo("(invalid extra field)")))
         },
+        test("option syncstate - 1") {
+          final case class SyncState(
+            @jsonField("next_batch") nextBatch: String,
+            @jsonField("account_data") accountData: Option[String]
+          )
+
+          implicit val syncStateDecoder: JsonDecoder[SyncState] = DeriveJsonDecoder.gen
+
+          val content = """ 
+{
+    "next_batch": "s737036_20146721_28996_716058_326898_115_59067_740531_0",
+    "device_unused_fallback_key_types": []
+}
+            """
+          assert(content.fromJson[Json].flatMap(_.as[SyncState](syncStateDecoder)))(
+            isRight(equalTo(SyncState("s737036_20146721_28996_716058_326898_115_59067_740531_0", None)))
+          )
+        },
+        test("option syncstate - 2") {
+          final case class SyncState(
+            @jsonField("next_batch") nextBatch: String,
+            @jsonField("account_data") accountData: Option[String]
+          )
+
+          implicit val syncStateDecoder: JsonDecoder[SyncState] = DeriveJsonDecoder.gen
+
+          val content = """ 
+{
+    "next_batch": "s737036_20146721_28996_716058_326898_115_59067_740531_0",
+    "device_unused_fallback_key_types": []
+}
+            """
+          assert(content.fromJson[SyncState](syncStateDecoder))(
+            isRight(equalTo(SyncState("s737036_20146721_28996_716058_326898_115_59067_740531_0", None)))
+          )
+        },
         test("option") {
           case class WithOpt(id: Int, opt: Option[Int])
           implicit val decoder: JsonDecoder[WithOpt] = DeriveJsonDecoder.gen
-- 
2.34.1


```

And then ran the tests with `sbt '++3.1.3 zioJsonJVM/test'` and the first test did not pass, the second one did pass.
I totally get that the first way of writing the code with the flatMap is not a good idea, and probably wrong, but it passes on 2.12 and 2.13 but not in 3.0. The following patch shows the same behavior with the current `option` test:
```diff
From 5c1567ecd35774f92f4b895df1d0dc83ec083dd8 Mon Sep 17 00:00:00 2001
From: ex0ns <mail@mail.com>
Date: Thu, 10 Nov 2022 21:03:14 +0100
Subject: [PATCH] spec

---
 zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala b/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala
index e48865b..93f7369 100644
--- a/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala
+++ b/zio-json/shared/src/test/scala/zio/json/DecoderSpec.scala
@@ -75,7 +75,11 @@ object DecoderSpec extends ZIOSpecDefault {
           implicit val decoder: JsonDecoder[WithOpt] = DeriveJsonDecoder.gen
 
           assert("""{ "id": 1, "opt": 42 }""".fromJson[WithOpt])(isRight(equalTo(WithOpt(1, Some(42))))) &&
-          assert("""{ "id": 1 }""".fromJson[WithOpt])(isRight(equalTo(WithOpt(1, None))))
+          assert("""{ "id": 1, "opt": 42 }""".fromJson[Json].flatMap(_.as[WithOpt]))(
+            isRight(equalTo(WithOpt(1, Some(42))))
+          ) &&
+          assert("""{ "id": 1 }""".fromJson[WithOpt])(isRight(equalTo(WithOpt(1, None)))) &&
+          assert("""{ "id": 1 }""".fromJson[Json].flatMap(_.as[WithOpt]))(isRight(equalTo(WithOpt(1, None))))
         },
         test("default field value") {
           import exampleproducts._
-- 
2.34.1


```

Edit: after a bit of investigation, this is coming from the macro derivation of `fromJsonAst` that was not updated when the version for 2.13 was, I will open a PR soon.
